# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import SDKClient
from msrest import Serializer, Deserializer

from ._configuration import azureactivedirectoryClientConfiguration
from .operations import Operations
from .operations import DiagnosticSettingsOperations
from .operations import DiagnosticSettingsCategoryOperations
from . import models


class azureactivedirectoryClient(SDKClient):
    """Azure Active Directory Client.

    :ivar config: Configuration for client.
    :vartype config: azureactivedirectoryClientConfiguration

    :ivar operations: Operations operations
    :vartype operations: microsoft.aadiam.operations.Operations
    :ivar diagnostic_settings: DiagnosticSettings operations
    :vartype diagnostic_settings: microsoft.aadiam.operations.DiagnosticSettingsOperations
    :ivar diagnostic_settings_category: DiagnosticSettingsCategory operations
    :vartype diagnostic_settings_category: microsoft.aadiam.operations.DiagnosticSettingsCategoryOperations

    :param credentials: Credentials needed for the client to connect to Azure.
    :type credentials: :mod:`A msrestazure Credentials
     object<msrestazure.azure_active_directory>`
    :param str base_url: Service URL
    """

    def __init__(
            self, credentials, base_url=None):

        self.config = azureactivedirectoryClientConfiguration(credentials, base_url)
        super(azureactivedirectoryClient, self).__init__(self.config.credentials, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = '2017-04-01'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.operations = Operations(
            self._client, self.config, self._serialize, self._deserialize)
        self.diagnostic_settings = DiagnosticSettingsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.diagnostic_settings_category = DiagnosticSettingsCategoryOperations(
            self._client, self.config, self._serialize, self._deserialize)
