# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import DiagnosticSettingsCategoryResource
    from ._models_py3 import DiagnosticSettingsCategoryResourceCollection
    from ._models_py3 import DiagnosticSettingsResource
    from ._models_py3 import DiagnosticSettingsResourceCollection
    from ._models_py3 import Display
    from ._models_py3 import ErrorDefinition
    from ._models_py3 import ErrorResponse, ErrorResponseException
    from ._models_py3 import LogSettings
    from ._models_py3 import OperationsDiscovery
    from ._models_py3 import OperationsDiscoveryCollection
    from ._models_py3 import ProxyOnlyResource
    from ._models_py3 import RetentionPolicy
except (SyntaxError, ImportError):
    from ._models import DiagnosticSettingsCategoryResource
    from ._models import DiagnosticSettingsCategoryResourceCollection
    from ._models import DiagnosticSettingsResource
    from ._models import DiagnosticSettingsResourceCollection
    from ._models import Display
    from ._models import ErrorDefinition
    from ._models import ErrorResponse, ErrorResponseException
    from ._models import LogSettings
    from ._models import OperationsDiscovery
    from ._models import OperationsDiscoveryCollection
    from ._models import ProxyOnlyResource
    from ._models import RetentionPolicy
from ._azureactivedirectory_client_enums import (
    Category,
    CategoryType,
)

__all__ = [
    'DiagnosticSettingsCategoryResource',
    'DiagnosticSettingsCategoryResourceCollection',
    'DiagnosticSettingsResource',
    'DiagnosticSettingsResourceCollection',
    'Display',
    'ErrorDefinition',
    'ErrorResponse', 'ErrorResponseException',
    'LogSettings',
    'OperationsDiscovery',
    'OperationsDiscoveryCollection',
    'ProxyOnlyResource',
    'RetentionPolicy',
    'Category',
    'CategoryType',
]
